server:
  port: 8443
  ssl:
    key-store: classpath:cfq.key
    key-store-password: 123456
    key-password: 123456

http:
  port: 9090

permit:
  urls: /users/login

spring:
  application:
    name: user-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/study_security?characterEncoding=UTF-8&useSSL=false
    username: root
    password: mlsql
  jpa:
    generate-ddl: true
    show-sql: true
